import { OrgType, OrgSequence } from '@/const/index'

export const OrgOptions = [
  {
    condition: {
      orgSequence: OrgSequence.Division
    },
    options: [{
      name: '指挥员',
      group: '首长机关',
      orgSequence: OrgSequence.Division,
      orgType: OrgType.LeaderOffice,
      orgMajors: ['指挥员']
    }, {
      name: '参谋部',
      group: '首长机关',
      orgSequence: OrgSequence.Division,
      orgType: OrgType.LeaderOffice,
      orgMajors: []
    }, {
      name: '政治工作部',
      group: '首长机关',
      orgSequence: OrgSequence.Division,
      orgType: OrgType.LeaderOffice,
      orgMajors: []
    }, {
      name: '保障部',
      group: '首长机关',
      orgSequence: OrgSequence.Division,
      orgType: OrgType.LeaderOffice,
      orgMajors: []
    }, {
      name: '作战勤务处',
      group: '参谋部',
      orgSequence: OrgSequence.Division,
      orgType: OrgType.Department,
      orgMajors: ['作战勤务']
    }, {
      name: '作训处',
      group: '参谋部',
      orgSequence: OrgSequence.Division,
      orgType: OrgType.Department,
      orgMajors: ['作训']
    }, {
      name: '作战勤务指挥中心',
      group: '参谋部',
      orgSequence: OrgSequence.Division,
      orgType: OrgType.Department,
      orgMajors: ['作战勤务']
    }, {
      name: '综合信息保障中心',
      group: '参谋部',
      orgSequence: OrgSequence.Division,
      orgType: OrgType.Department,
      orgMajors: ['信息通信']
    }, {
      name: '情报室',
      group: '参谋部',
      orgSequence: OrgSequence.Division,
      orgType: OrgType.Department,
      orgMajors: ['情报']
    }, {
      name: '信息运维室',
      group: '参谋部',
      orgSequence: OrgSequence.Division,
      orgType: OrgType.Department,
      orgMajors: ['信息通信']
    }, {
      name: '数据室',
      group: '参谋部',
      orgSequence: OrgSequence.Division,
      orgType: OrgType.Department,
      orgMajors: ['信息通信']
    }, {
      name: '情报处',
      group: '参谋部',
      orgSequence: OrgSequence.Division,
      orgType: OrgType.Department,
      orgMajors: ['情报']
    }, {
      name: '信息通信处',
      group: '参谋部',
      orgSequence: OrgSequence.Division,
      orgType: OrgType.Department,
      orgMajors: ['信息通信']
    }, {
      name: '训练处',
      group: '参谋部',
      orgSequence: OrgSequence.Division,
      orgType: OrgType.Department,
      orgMajors: ['训练']
    }, {
      name: '部队管理处',
      group: '参谋部',
      orgSequence: OrgSequence.Division,
      orgType: OrgType.Department,
      orgMajors: ['部队管理']
    }, {
      name: '机要处',
      group: '参谋部',
      orgSequence: OrgSequence.Division,
      orgType: OrgType.Department,
      orgMajors: ['机要']
    }, {
      name: '直属工作处',
      group: '参谋部',
      orgSequence: OrgSequence.Division,
      orgType: OrgType.Department,
      orgMajors: []
    }, {
      name: '组织处',
      group: '政治工作部',
      orgSequence: OrgSequence.Division,
      orgType: OrgType.Department,
      orgMajors: ['组织']
    }, {
      name: '人力资源处',
      group: '政治工作部',
      orgSequence: OrgSequence.Division,
      orgType: OrgType.Department,
      orgMajors: ['人力资源']
    }, {
      name: '宣传处',
      group: '政治工作部',
      orgSequence: OrgSequence.Division,
      orgType: OrgType.Department,
      orgMajors: ['宣传']
    }, {
      name: '纪检监察处',
      group: '政治工作部',
      orgSequence: OrgSequence.Division,
      orgType: OrgType.Department,
      orgMajors: []
    }, {
      name: '保卫处',
      group: '政治工作部',
      orgSequence: OrgSequence.Division,
      orgType: OrgType.Department,
      orgMajors: ['保卫']
    }, {
      name: '文化站',
      group: '政治工作部',
      orgSequence: OrgSequence.Division,
      orgType: OrgType.Department,
      orgMajors: []
    }, {
      name: '新闻站',
      group: '政治工作部',
      orgSequence: OrgSequence.Division,
      orgType: OrgType.Department,
      orgMajors: []
    }, {
      name: '电视站',
      group: '政治工作部',
      orgSequence: OrgSequence.Division,
      orgType: OrgType.Department,
      orgMajors: []
    }, {
      name: '战勤计划处',
      group: '保障部',
      orgSequence: OrgSequence.Division,
      orgType: OrgType.Department,
      orgMajors: ['战勤计划']
    }, {
      name: '财务处',
      group: '保障部',
      orgSequence: OrgSequence.Division,
      orgType: OrgType.Department,
      orgMajors: ['财务']
    }, {
      name: '军需营房处',
      group: '保障部',
      orgSequence: OrgSequence.Division,
      orgType: OrgType.Department,
      orgMajors: ['军需营房']
    }, {
      name: '卫生处',
      group: '保障部',
      orgSequence: OrgSequence.Division,
      orgType: OrgType.Department,
      orgMajors: ['卫生']
    }, {
      name: '运输投送处',
      group: '保障部',
      orgSequence: OrgSequence.Division,
      orgType: OrgType.Department,
      orgMajors: ['运输投送']
    }, {
      name: '装备保障处',
      group: '保障部',
      orgSequence: OrgSequence.Division,
      orgType: OrgType.Department,
      orgMajors: ['装备保障']
    }]
  },

  {
    condition: {
      orgSequence: OrgSequence.Brigade
    },
    options: [{
      name: '指挥员',
      group: '首长机关',
      orgSequence: OrgSequence.Brigade,
      orgType: OrgType.LeaderOffice,
      orgMajors: ['指挥员']
    }, {
      name: '参谋部',
      group: '首长机关',
      orgSequence: OrgSequence.Brigade,
      orgType: OrgType.LeaderOffice,
      orgMajors: []
    }, {
      name: '政治工作部',
      group: '首长机关',
      orgSequence: OrgSequence.Brigade,
      orgType: OrgType.LeaderOffice,
      orgMajors: []
    }, {
      name: '保障部',
      group: '首长机关',
      orgSequence: OrgSequence.Brigade,
      orgType: OrgType.LeaderOffice,
      orgMajors: []
    }, {
      name: '作训科',
      group: '参谋部',
      orgSequence: OrgSequence.Regiment,
      orgType: OrgType.Department,
      orgMajors: ['作训']
    }, {
      name: '侦察科',
      group: '参谋部',
      orgSequence: OrgSequence.Regiment,
      orgType: OrgType.Department,
      orgMajors: ['侦察']
    }, {
      name: '信息通信科',
      group: '参谋部',
      orgSequence: OrgSequence.Regiment,
      orgType: OrgType.Department,
      orgMajors: ['信息通信']
    }, {
      name: '部队管理科',
      group: '参谋部',
      orgSequence: OrgSequence.Regiment,
      orgType: OrgType.Department,
      orgMajors: ['部队管理']
    }, {
      name: '机要科',
      group: '参谋部',
      orgSequence: OrgSequence.Regiment,
      orgType: OrgType.Department,
      orgMajors: ['机要']
    }, {
      name: '组织科',
      group: '政治工作部',
      orgSequence: OrgSequence.Regiment,
      orgType: OrgType.Department,
      orgMajors: ['组织']
    }, {
      name: '人力资源科',
      group: '政治工作部',
      orgSequence: OrgSequence.Regiment,
      orgType: OrgType.Department,
      orgMajors: ['人力资源']
    }, {
      name: '保卫科',
      group: '政治工作部',
      orgSequence: OrgSequence.Regiment,
      orgType: OrgType.Department,
      orgMajors: ['保卫']
    }, {
      name: '纪检监察科',
      group: '政治工作部',
      orgSequence: OrgSequence.Regiment,
      orgType: OrgType.Department,
      orgMajors: []
    }, {
      name: '宣传科',
      group: '政治工作部',
      orgSequence: OrgSequence.Regiment,
      orgType: OrgType.Department,
      orgMajors: ['宣传']
    }, {
      name: '战勤计划科',
      group: '保障部',
      orgSequence: OrgSequence.Regiment,
      orgType: OrgType.Department,
      orgMajors: ['战勤计划']
    }, {
      name: '军需营房科',
      group: '保障部',
      orgSequence: OrgSequence.Regiment,
      orgType: OrgType.Department,
      orgMajors: ['军需营房']
    }, {
      name: '运输投送科',
      group: '保障部',
      orgSequence: OrgSequence.Regiment,
      orgType: OrgType.Department,
      orgMajors: ['运输投送']
    }, {
      name: '财务科',
      group: '保障部',
      orgSequence: OrgSequence.Regiment,
      orgType: OrgType.Department,
      orgMajors: ['财务']
    }, {
      name: '装备保障科',
      group: '保障部',
      orgSequence: OrgSequence.Regiment,
      orgType: OrgType.Department,
      orgMajors: ['装备保障']
    }]
  },

  {
    condition: {
      orgSequences: [OrgSequence.Regiment]
    },
    options: [{
      name: '指挥员',
      group: '首长机关',
      orgSequence: OrgSequence.Regiment,
      orgType: OrgType.LeaderOffice,
      orgMajors: ['指挥员']
    }, {
      name: '参谋部',
      group: '首长机关',
      orgSequence: OrgSequence.Regiment,
      orgType: OrgType.LeaderOffice,
      orgMajors: []
    }, {
      name: '政治工作处',
      group: '首长机关',
      orgSequence: OrgSequence.Regiment,
      orgType: OrgType.LeaderOffice,
      orgMajors: []
    }, {
      name: '保障处',
      group: '首长机关',
      orgSequence: OrgSequence.Regiment,
      orgType: OrgType.LeaderOffice,
      orgMajors: []
    }, {
      name: '作训股',
      group: '参谋部',
      orgSequence: OrgSequence.Regiment,
      orgType: OrgType.Department,
      orgMajors: ['作训']
    }, {
      name: '侦察股',
      group: '参谋部',
      orgSequence: OrgSequence.Regiment,
      orgType: OrgType.Department,
      orgMajors: ['侦察']
    }, {
      name: '信息通信股',
      group: '参谋部',
      orgSequence: OrgSequence.Regiment,
      orgType: OrgType.Department,
      orgMajors: ['信息通信']
    }, {
      name: '部队管理股',
      group: '参谋部',
      orgSequence: OrgSequence.Regiment,
      orgType: OrgType.Department,
      orgMajors: ['部队管理']
    }, {
      name: '机要股',
      group: '参谋部',
      orgSequence: OrgSequence.Regiment,
      orgType: OrgType.Department,
      orgMajors: ['机要']
    }, {
      name: '宣传保卫股',
      group: '政治工作处',
      orgSequence: OrgSequence.Regiment,
      orgType: OrgType.Department,
      orgMajors: ['宣传', '保卫']
    }, {
      name: '人力资源股',
      group: '政治工作处',
      orgSequence: OrgSequence.Regiment,
      orgType: OrgType.Department,
      orgMajors: ['人力资源']
    }, {
      name: '组织纪检股',
      group: '政治工作处',
      orgSequence: OrgSequence.Regiment,
      orgType: OrgType.Department,
      orgMajors: ['组织']
    }, {
      name: '战勤计划股',
      group: '保障处',
      orgSequence: OrgSequence.Regiment,
      orgType: OrgType.Department,
      orgMajors: ['战勤计划']
    }, {
      name: '后勤保障股',
      group: '保障处',
      orgSequence: OrgSequence.Regiment,
      orgType: OrgType.Department,
      orgMajors: ['财务', '军需营房', '运输投送']
    }, {
      name: '装备保障股',
      group: '保障处',
      orgSequence: OrgSequence.Regiment,
      orgType: OrgType.Department,
      orgMajors: ['装备保障']
    }]
  },

  {
    condition: {
      orgSequence: OrgSequence.Battalion
    },
    options: [{
      name: '指挥员',
      orgSequence: OrgSequence.Battalion,
      orgType: OrgType.Department,
      orgMajors: []
    }]
  },

  {
    condition: {
      orgSequence: OrgSequence.Company
    },
    options: [{
      name: '指挥员',
      orgSequence: OrgSequence.Company,
      orgType: OrgType.Department,
      orgMajors: []
    }, {
      name: '特战排',
      orgSequence: OrgSequence.Squad,
      orgType: OrgType.UnitForce,
      orgMajors: [],
      orgCategory: '执勤支队特战分队'
    }, {
      name: '应急班',
      orgSequence: OrgSequence.Squad,
      orgType: OrgType.UnitForce,
      orgMajors: [],
      orgCategory: '执勤支队应急分队'
    }, {
      name: '后勤班',
      orgSequence: OrgSequence.Squad,
      orgType: OrgType.UnitForce,
      orgMajors: []
    }, {
      name: '保障人员',
      orgSequence: OrgSequence.Squad,
      orgType: OrgType.UnitForce,
      orgMajors: []
    }]
  }
]
